/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://u625picxg5gpdcbd4o3fvxfi7q.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-1:89ecdbae-df27-4c6f-ba4f-ea83897d44c8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_EKzGe7te0",
    "aws_user_pools_web_client_id": "57jf7a2vfc5hvgcpqdl2ambeg3",
    "oauth": {
        "domain": "fs-mainn.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://forwardslash.ch/,http://localhost:3000/",
        "redirectSignOut": "https://forwardslash.ch/,http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cloud_logic_custom": []
};


export default awsmobile;
